const express = require('express');
const ExcelJS = require('exceljs');
const { authenticate } = require('../middleware/auth');
const { sendReminderEmail } = require('../services/email');

const router = express.Router();

// This is a special dev endpoint so the user can generate test emails on demand
router.get('/trigger-test-alert', authenticate, async (req, res) => {
  try {
    const db = req.app.locals.db;
    const today = new Date();
    const thirtyDaysFromNow = new Date(today.getTime() + (30 * 24 * 60 * 60 * 1000));
    const todayStr = today.toISOString().split('T')[0];
    const thirtyDaysStr = thirtyDaysFromNow.toISOString().split('T')[0];

    const upcomingProjects = db.prepare(`
      SELECT project_name, project_code, date_of_closing, report_status 
      FROM projects 
      WHERE date_of_closing >= ? AND date_of_closing <= ? 
      AND report_status != 'Completed'
    `).all(todayStr, thirtyDaysStr);

    const lowInventory = db.prepare(`
      SELECT item_name, inventory_class, qty, total_qty_in_stock
      FROM inventory
      WHERE CAST(total_qty_in_stock AS INTEGER) < 10
    `).all();

    let htmlContent = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0f172a;">LabPortal Automated Alerts (On-Demand Test)</h2>
        <p>This is your automated system reminder for laboratory resources requiring attention.</p>
    `;

    if (upcomingProjects.length > 0) {
      htmlContent += `
        <h3 style="color: #f59e0b; border-bottom: 2px solid #f59e0b; padding-bottom: 5px;">
          ⚠️ Projects Nearing Closing Date
        </h3>
        <ul>
      `;
      upcomingProjects.forEach(p => {
        htmlContent += `<li><strong>${p.project_name}</strong> (${p.project_code}) closes on <strong>${p.date_of_closing}</strong>. Status: ${p.report_status}</li>`;
      });
      htmlContent += `</ul>`;
    }

    if (lowInventory.length > 0) {
      htmlContent += `
        <h3 style="color: #ef4444; border-bottom: 2px solid #ef4444; padding-bottom: 5px;">
          📉 Low Inventory Alerts
        </h3>
        <ul>
      `;
      lowInventory.forEach(item => {
        htmlContent += `<li><strong>${item.item_name}</strong> (${item.inventory_class}): Only <strong>${item.total_qty_in_stock}</strong> left in stock.</li>`;
      });
      htmlContent += `</ul>`;
    }

    htmlContent += `
        <br/>
        <p style="font-size: 0.8em; color: #64748b;">This email was automatically generated by the ICAR-IIRR LabPortal System.</p>
      </div>
    `;

    const adminEmail = process.env.ADMIN_EMAIL || 'admin@icariirr.test'; 
    const info = await sendReminderEmail(adminEmail, 'LabPortal Alert: Upcoming Deadlines & Low Inventory', htmlContent);
    const nodemailer = require('nodemailer');
    const previewUrl = nodemailer.getTestMessageUrl(info);

    res.json({ success: true, message: 'Test email generated successfully!', previewUrl, htmlContent });
  } catch (err) {
    console.error('Error generating test email:', err.message);
    res.status(500).json({ error: 'Failed to generate test email.' });
  }
});

/**
 * Resource configurations for building queries dynamically.
 */
const RESOURCE_CONFIG = {
  people: {
    table: 'people',
    columns: ['id', 'name', 'category', 'email', 'phone', 'date_of_joining', 'date_of_relieving', 'status'],
    excelHeaders: [
      { header: 'ID', key: 'id', width: 8 },
      { header: 'Name', key: 'name', width: 30 },
      { header: 'Category', key: 'category', width: 20 },
      { header: 'Email', key: 'email', width: 30 },
      { header: 'Phone', key: 'phone', width: 15 },
      { header: 'Date of Joining', key: 'date_of_joining', width: 18 },
      { header: 'Date of Relieving', key: 'date_of_relieving', width: 18 },
      { header: 'Status', key: 'status', width: 12 }
    ],
    filters: {
      search: (params) => {
        params.conditions.push('(name LIKE ? OR email LIKE ? OR phone LIKE ?)');
        const term = `%${params.value}%`;
        params.values.push(term, term, term);
      },
      category: (params) => {
        params.conditions.push('category = ?');
        params.values.push(params.value);
      },
      status: (params) => {
        params.conditions.push('status = ?');
        params.values.push(params.value);
      }
    }
  },
  projects: {
    table: 'projects',
    columns: ['id', 'project_name', 'project_code', 'type_of_project', 'funding_source', 'date_of_start', 'date_of_closing', 'report_status', 'status'],
    excelHeaders: [
      { header: 'ID', key: 'id', width: 8 },
      { header: 'Project Name', key: 'project_name', width: 45 },
      { header: 'Project Code', key: 'project_code', width: 18 },
      { header: 'Type', key: 'type_of_project', width: 15 },
      { header: 'Funding Source', key: 'funding_source', width: 25 },
      { header: 'Start Date', key: 'date_of_start', width: 15 },
      { header: 'Closing Date', key: 'date_of_closing', width: 15 },
      { header: 'Report Status', key: 'report_status', width: 15 },
      { header: 'Status', key: 'status', width: 12 }
    ],
    filters: {
      search: (params) => {
        params.conditions.push('(project_name LIKE ? OR project_code LIKE ? OR funding_source LIKE ?)');
        const term = `%${params.value}%`;
        params.values.push(term, term, term);
      },
      type: (params) => {
        params.conditions.push('type_of_project = ?');
        params.values.push(params.value);
      },
      status: (params) => {
        params.conditions.push('status = ?');
        params.values.push(params.value);
      },
      report_status: (params) => {
        params.conditions.push('report_status = ?');
        params.values.push(params.value);
      }
    }
  },
  publications: {
    table: 'publications',
    selectSql: `
      SELECT pub.id, pub.title, proj.project_name, pub.year, pub.journal,
             pub.naas_score, pub.authors, pub.project_id
      FROM publications pub
      LEFT JOIN projects proj ON pub.project_id = proj.id
    `,
    columns: ['id', 'title', 'project_name', 'year', 'journal', 'naas_score', 'authors'],
    excelHeaders: [
      { header: 'ID', key: 'id', width: 8 },
      { header: 'Title', key: 'title', width: 55 },
      { header: 'Project', key: 'project_name', width: 35 },
      { header: 'Year', key: 'year', width: 8 },
      { header: 'Journal', key: 'journal', width: 40 },
      { header: 'NAAS Score', key: 'naas_score', width: 12 },
      { header: 'Authors', key: 'authors', width: 40 }
    ],
    filters: {
      search: (params) => {
        params.conditions.push('(pub.title LIKE ? OR pub.journal LIKE ? OR pub.authors LIKE ?)');
        const term = `%${params.value}%`;
        params.values.push(term, term, term);
      },
      year: (params) => {
        params.conditions.push('pub.year = ?');
        params.values.push(parseInt(params.value, 10));
      },
      project_id: (params) => {
        params.conditions.push('pub.project_id = ?');
        params.values.push(parseInt(params.value, 10));
      }
    }
  },
  inventory: {
    table: 'inventory',
    columns: ['id', 'item_name', 'inventory_class', 'date_of_purchase', 'make', 'model', 'cat_no', 'qty', 'price', 'total_qty_in_stock'],
    excelHeaders: [
      { header: 'ID', key: 'id', width: 8 },
      { header: 'Item Name', key: 'item_name', width: 35 },
      { header: 'Class', key: 'inventory_class', width: 22 },
      { header: 'Date of Purchase', key: 'date_of_purchase', width: 18 },
      { header: 'Make', key: 'make', width: 20 },
      { header: 'Model', key: 'model', width: 18 },
      { header: 'Cat. No.', key: 'cat_no', width: 18 },
      { header: 'Qty', key: 'qty', width: 8 },
      { header: 'Price (₹)', key: 'price', width: 14 },
      { header: 'In Stock', key: 'total_qty_in_stock', width: 10 }
    ],
    filters: {
      search: (params) => {
        params.conditions.push('(item_name LIKE ? OR make LIKE ? OR model LIKE ? OR cat_no LIKE ?)');
        const term = `%${params.value}%`;
        params.values.push(term, term, term, term);
      },
      inventory_class: (params) => {
        params.conditions.push('inventory_class = ?');
        params.values.push(params.value);
      }
    }
  }
};

/**
 * Build filtered SQL query based on resource config and query params.
 */
function buildFilteredQuery(config, query) {
  const conditions = [];
  const values = [];

  for (const [key, filterFn] of Object.entries(config.filters)) {
    if (query[key]) {
      filterFn({ conditions, values, value: query[key] });
    }
  }

  let sql;
  if (config.selectSql) {
    sql = config.selectSql;
  } else {
    sql = `SELECT * FROM ${config.table}`;
  }

  if (conditions.length > 0) {
    sql += ' WHERE ' + conditions.join(' AND ');
  }

  sql += ' ORDER BY id DESC';

  return { sql, values };
}

/**
 * GET /api/reports/:resource
 * Return filtered data for the given resource type.
 */
router.get('/:resource', authenticate, (req, res) => {
  try {
    const { resource } = req.params;
    const config = RESOURCE_CONFIG[resource];

    if (!config) {
      return res.status(400).json({
        error: `Invalid resource type: ${resource}. Valid types: ${Object.keys(RESOURCE_CONFIG).join(', ')}`
      });
    }

    const db = req.app.locals.db;
    const { sql, values } = buildFilteredQuery(config, req.query);

    const data = db.prepare(sql).all(...values);
    res.json({ data, total: data.length, resource });
  } catch (err) {
    console.error(`Error generating report for ${req.params.resource}:`, err.message);
    res.status(500).json({ error: 'Failed to generate report.' });
  }
});

/**
 * GET /api/reports/:resource/export
 * Generate and return an Excel file using exceljs with proper headers and formatting.
 */
router.get('/:resource/export', authenticate, async (req, res) => {
  try {
    const { resource } = req.params;
    const config = RESOURCE_CONFIG[resource];

    if (!config) {
      return res.status(400).json({
        error: `Invalid resource type: ${resource}. Valid types: ${Object.keys(RESOURCE_CONFIG).join(', ')}`
      });
    }

    const db = req.app.locals.db;
    const { sql, values } = buildFilteredQuery(config, req.query);
    const data = db.prepare(sql).all(...values);

    // Create Excel workbook
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'ICAR-IIRR Lab Portal';
    workbook.created = new Date();

    const sheetName = resource.charAt(0).toUpperCase() + resource.slice(1);
    const worksheet = workbook.addWorksheet(sheetName);

    // Set columns from config
    worksheet.columns = config.excelHeaders;

    // Style the header row
    const headerRow = worksheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF2E7D32' }
    };
    headerRow.alignment = { vertical: 'middle', horizontal: 'center' };
    headerRow.height = 24;

    // Add data rows
    data.forEach((row, index) => {
      const dataRow = worksheet.addRow(row);

      // Alternate row background colors for readability
      if (index % 2 === 1) {
        dataRow.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF1F8E9' }
        };
      }

      dataRow.alignment = { vertical: 'middle' };
    });

    // Add borders to all cells with data
    const totalRows = data.length + 1;
    const totalCols = config.excelHeaders.length;
    for (let row = 1; row <= totalRows; row++) {
      for (let col = 1; col <= totalCols; col++) {
        const cell = worksheet.getCell(row, col);
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFB0BEC5' } },
          left: { style: 'thin', color: { argb: 'FFB0BEC5' } },
          bottom: { style: 'thin', color: { argb: 'FFB0BEC5' } },
          right: { style: 'thin', color: { argb: 'FFB0BEC5' } }
        };
      }
    }

    // Auto-filter on the header row
    worksheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: totalCols }
    };

    // Freeze the header row
    worksheet.views = [{ state: 'frozen', ySplit: 1 }];

    // Set response headers
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `${resource}_report_${timestamp}.xlsx`;
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    // Write workbook to response
    await workbook.xlsx.write(res);
    res.end();
  } catch (err) {
    console.error(`Error exporting ${req.params.resource}:`, err.message);
    res.status(500).json({ error: 'Failed to export report.' });
  }
});

const docx = require('docx');
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, BorderStyle, WidthType } = docx;

/**
 * GET /api/reports/:resource/export-word
 * Generate and return an MS Word file using docx with proper tables.
 */
router.get('/:resource/export-word', authenticate, async (req, res) => {
  try {
    const { resource } = req.params;
    const config = RESOURCE_CONFIG[resource];

    if (!config) {
      return res.status(400).json({
        error: `Invalid resource type: ${resource}. Valid types: ${Object.keys(RESOURCE_CONFIG).join(', ')}`
      });
    }

    const db = req.app.locals.db;
    const { sql, values } = buildFilteredQuery(config, req.query);
    const data = db.prepare(sql).all(...values);

    // Create table header
    const tableHeaderRow = new TableRow({
      children: config.excelHeaders.map(col => new TableCell({
        children: [new Paragraph({
          children: [new TextRun({ text: col.header, bold: true, color: "FFFFFF" })],
        })],
        shading: {
          fill: "2E7D32",
        },
        margins: { top: 100, bottom: 100, left: 100, right: 100 }
      })),
    });

    // Create table rows
    const tableDataRows = data.map((row, index) => {
      return new TableRow({
        children: config.excelHeaders.map(col => new TableCell({
          children: [new Paragraph({ text: String(row[col.key] || '') })],
          shading: {
            fill: index % 2 === 1 ? "F1F8E9" : "FFFFFF",
          },
          margins: { top: 100, bottom: 100, left: 100, right: 100 }
        })),
      });
    });

    const reportTable = new Table({
      rows: [tableHeaderRow, ...tableDataRows],
      width: {
        size: 100,
        type: WidthType.PERCENTAGE,
      },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "B0BEC5" },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "B0BEC5" },
        left: { style: BorderStyle.SINGLE, size: 1, color: "B0BEC5" },
        right: { style: BorderStyle.SINGLE, size: 1, color: "B0BEC5" },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: "B0BEC5" },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: "B0BEC5" },
      },
    });

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: `ICAR-IIRR LabPortal: ${resource.charAt(0).toUpperCase() + resource.slice(1)} Report`,
                bold: true,
                size: 32,
              }),
            ],
            spacing: { after: 300 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated on: ${new Date().toLocaleString()}`,
                size: 24,
                color: "555555"
              }),
            ],
            spacing: { after: 300 },
          }),
          reportTable,
        ],
      }],
    });

    const buffer = await Packer.toBuffer(doc);
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `${resource}_report_${timestamp}.docx`;
    
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(buffer);
  } catch (err) {
    console.error(`Error exporting ${req.params.resource} to Word:`, err.message);
    res.status(500).json({ error: 'Failed to export report to Word.' });
  }
});

module.exports = router;
