const cron = require('node-cron');
const db = require('better-sqlite3')('db/laboratory.db');
const { sendReminderEmail } = require('./email');

function checkDeadlinesAndInventory() {
  console.log('⏳ Running scheduled background checks for deadlines and inventory...');
  
  try {
    // 1. Check Projects Closing Soon (within 30 days or less, and not yet closed)
    // For simplicity in SQLite, we look for projects whose closing date is approaching
    // A robust query uses strftime for date math, but simple string comparison works for YYYY-MM-DD
    const today = new Date();
    const thirtyDaysFromNow = new Date(today.getTime() + (30 * 24 * 60 * 60 * 1000));
    const todayStr = today.toISOString().split('T')[0];
    const thirtyDaysStr = thirtyDaysFromNow.toISOString().split('T')[0];

    const upcomingProjects = db.prepare(`
      SELECT project_name, project_code, date_of_closing, report_status 
      FROM projects 
      WHERE date_of_closing >= ? AND date_of_closing <= ? 
      AND report_status != 'Completed'
    `).all(todayStr, thirtyDaysStr);

    // 2. Check Low Inventory (Threshold: < 10)
    const lowInventory = db.prepare(`
      SELECT item_name, inventory_class, qty, total_qty_in_stock
      FROM inventory
      WHERE CAST(total_qty_in_stock AS INTEGER) < 10
    `).all();

    // 3. Compile and Send Email if there are alerts
    if (upcomingProjects.length > 0 || lowInventory.length > 0) {
      let htmlContent = `
        <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #0f172a;">LabPortal Automated Alerts</h2>
          <p>This is your automated system reminder for laboratory resources requiring attention.</p>
      `;

      if (upcomingProjects.length > 0) {
        htmlContent += `
          <h3 style="color: #f59e0b; border-bottom: 2px solid #f59e0b; padding-bottom: 5px;">
            ⚠️ Projects Nearing Closing Date
          </h3>
          <ul>
        `;
        upcomingProjects.forEach(p => {
          htmlContent += `<li><strong>${p.project_name}</strong> (${p.project_code}) closes on <strong>${p.date_of_closing}</strong>. Status: ${p.report_status}</li>`;
        });
        htmlContent += `</ul>`;
      }

      if (lowInventory.length > 0) {
        htmlContent += `
          <h3 style="color: #ef4444; border-bottom: 2px solid #ef4444; padding-bottom: 5px;">
            📉 Low Inventory Alerts
          </h3>
          <ul>
        `;
        lowInventory.forEach(item => {
          htmlContent += `<li><strong>${item.item_name}</strong> (${item.inventory_class}): Only <strong>${item.total_qty_in_stock}</strong> left in stock.</li>`;
        });
        htmlContent += `</ul>`;
      }

      htmlContent += `
          <br/>
          <p style="font-size: 0.8em; color: #64748b;">This email was automatically generated by the ICAR-IIRR LabPortal System.</p>
        </div>
      `;

      const adminEmail = process.env.ADMIN_EMAIL || 'admin@icariirr.test'; 
      sendReminderEmail(adminEmail, 'LabPortal Alert: Upcoming Deadlines & Low Inventory', htmlContent);
    } else {
      console.log('✅ Background check complete. No alerts needed today.');
    }
  } catch (error) {
    console.error('Error during scheduled checks:', error);
  }
}

// Initialize cron jobs
function initCronJobs() {
  // Run every day at 08:00 AM
  // For testing purposes right now, we can run it once on startup, 
  // or set it to run every minute if we wanted rapid testing (e.g., '* * * * *').
  
  // Schedule for 8 AM daily
  cron.schedule('0 8 * * *', () => {
    checkDeadlinesAndInventory();
  });
  
  console.log('✅ Scheduled background cron jobs initialized (Daily at 8:00 AM)');
  
  // Force a test run 5 seconds after boot just to verify the ethereal link works!
  setTimeout(() => {
    console.log('[TESTING] Forcing initial run of background checks to verify email delivery...');
    checkDeadlinesAndInventory();
  }, 5000);
}

module.exports = { initCronJobs, checkDeadlinesAndInventory };
